#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Autostart apps
feh --bg-fill $HOME/walls/01.png &
$HOME/.config/polybar/launch.sh &
$HOME/.config/bspwm/script/bspwm_workspace &
#picom -b &
#redshift &

# Fix cursor
xsetroot -cursor_name left_ptr &

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 &

bspc config border_width            3
#bspc config border_radius	    6
bspc config window_gap              12
bspc config split_ratio             0.50

bspc config borderless_monocle   	false
bspc config gapless_monocle      	false
bspc config focus_follows_pointer	true

#bspc config top_padding            60
bspc config bottom_padding         40
bspc config left_padding           8
bspc config right_padding          8

# focused: A client which currently has the focus
bspc config focused_border_color "#bf616a"
# unfocused: A client which is not the focused
bspc config normal_border_color "#282A36"
#bspc config active_border_color "#ebdbb2"

# Window rule
# bspc rule -a <WM_CLASS> state=floating rectangle=<WxH+X+Y> where W=width, H=height, X+Y=position. 
bspc rule -a Thunar state=floating rectangle=1080x720+420+180
